### ISSUE TITLE
在 xcode14 beta6 版本代码报错

### ISSUE THREAD

**Issue by BestiOSDev** [growingio/growingio-sdk-ios-autotracker#222]
### 描述你的问题以及如何重现

error build: Undefined symbol: _OBJC_CLASS_$_GrowingTrackConfiguration

### 请提供您看到的异常或错误

```true
error build: Undefined symbol: _OBJC_CLASS_$_GrowingTrackConfiguration
```

### 请提供您发现此错误的环境

```true
error build: Undefined symbol: _OBJC_CLASS_$_GrowingTrackConfiguration
```

### 其他信息

error build: Undefined symbol: _OBJC_CLASS_$_GrowingTrackConfiguration

**Comment by YoloMao** [comment]
能否提供下具体的集成步骤，所使用语言 (Swift / Objective-C)，是否必现
当前工程在 Xcode 13 是否能够正常运行 @BestiOSDev

**Comment by BestiOSDev** [comment]
在 xocd13 上正常运行, xcod14beta 版本 有几个组件依赖到 GrowingAnalytics-cdp 就编译不通过.你们有空研究下 最新 xcode14 怎么编译. 我猜测可能就是 GrowingAnalytics-cdp 依赖到 GrowingAnalytics 里边的类, 采用 #import "GrowingTrackerCore/Public/GrowingTrackConfiguration.h" 这种方式引入, 导致在 swift 里边编译不通过.
在 xcode13 上通过设置 CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES, 解决了找不到头文件的错误

**Comment by BestiOSDev** [comment]
下个月 9 月 10 号就开始苹果 WWDC 秋季发布会, 到时候最新iOS16 也该发布, 会有更多的开发者去适配 iOS16, 总不能下载使用 xcode14 编译代码不通过.

**Comment by YoloMao** [comment]
参考 SDK 的集成文档中的[解决方案](https://growingio.github.io/growingio-sdk-docs/docs/ios/base#include-of-non-modular-header-inside-framework-module-%E6%8A%A5%E9%94%99%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88)，修改 `OTHER_SWIFT_FLAGS`，试一下是否可行 @BestiOSDev

**Comment by BestiOSDev** [comment]
![image](https://user-images.githubusercontent.com/15530810/187387978-28a00998-635d-403b-93fd-53285487bfa3.png)
我们公司项目是 swift 为主要开发语言, 有个LEventTracking组件使用到了GrowingAnalytics和GrowingAnalytics_cdp, 在 xcode14  beta6 版本编译不通过, 在 xcode13.4.1 正常编译通过.

**Comment by YoloMao** [comment]
环境：
Xcode Version 14.0 beta 6 (14A5294g)
iPhone 12 Pro Version 16.0 (20A5349b)

经实际验证，使用 SDK 集成文档中的[解决方案](https://growingio.github.io/growingio-sdk-docs/docs/ios/base#include-of-non-modular-header-inside-framework-module-%E6%8A%A5%E9%94%99%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88) - 方式二，配置 `OTHER_SWIFT_FLAGS` 为 `-Xcc -Wno-error=non-modular-include-in-framework-module`，编译、运行正常。

请按照此方式进行集成使用

**Comment by YoloMao** [comment]
另外，Swift 项目推荐使用 SwiftPM 集成。集成文档可切换至 「Swift Package Manager 集成」 Tab 查看：https://growingio.github.io/growingio-sdk-docs/docs/ios/base#%E6%97%A0%E5%9F%8B%E7%82%B9-sdk-%E9%9B%86%E6%88%90

如因不可描述的网络问题，无法在 Xcode 中远端拉取 Package，可 git clone 至本地后，通过 Add Local... 选项进行本地集成。

**Comment by YoloMao** [comment]
@BestiOSDev 如果还有其他问题请通知我们，感谢你的意见。

**Comment by BestiOSDev** [comment]
thank you. 其他同事解决了这个问题, 非常感谢提供的帮助.
