### ISSUE TITLE
关于动态注入的js能否一并开源

### ISSUE THREAD

**Issue by shiflymoon** [growingio/growingio-sdk-ios-autotracker#81]
app中内嵌的网页页面，要实现追踪，应该是需要动态注入js代码，能否一并开源？谢谢！
比如window.GrowingWebViewJavascriptBridge.getDomTree具体实现？

**Comment by CaicaiNo** [comment]
@shiflymoon 关于JS那部分代码暂时还没有开源，后续也会开源
