### ISSUE TITLE
Page路径追踪问题

### ISSUE THREAD

**Issue by shiflymoon** [growingio/growingio-sdk-ios-autotracker#95]
目前页面路径的产生依赖于顶层UIViewController的viewDidAppear：，如果在路径中有一个或者几个类重写了VC的ViewDidAppear，并且没有调用super viewDidappear就会导致路径错误。这个地方是否参考mixpanel的基于VC的层级关系来产生页面路径会更合理。

**Comment by YoloMao** [comment]
在即将发布的 SDK 4.x 中，`page.path` 不再作为追踪项，取而代之的是用 `page.alias`，见：`GrowingPage`、`GrowingPageManager` 相关改动；
且 `page.alias` 由使用者传入，因此不再有此 issue 所描述的问题；

**Comment by YoloMao** [comment]
另外，Page 事件的发送由 `viewDidAppear` 行为触发，在与该 issue 相同使用者 App 代码场景下，可能会出现不发送 Page 的问题，这又是另外一个问题了。。。
如 Example 中，协议/接口 -> PAGE 请求 -> 第三行 Cell 所展示的场景：（所有 Cell 中的文字所描述的调用指 SDK 4.x 上调用 `autotrackPage` 接口）
<img width="364" alt="image" src="https://github.com/growingio/growingio-sdk-ios-autotracker/assets/16042670/dd15f7fe-0aee-4a08-bf5c-f3e854d2877c">
