### ISSUE TITLE
GrowingSwizzler Hook存在递归调用

### ISSUE THREAD

**Issue by shiflymoon** [growingio/growingio-sdk-ios-autotracker#97]
GrowingSwizzler Hook方案是有缺陷的，它按照参数个数把所有函数集中到某一个函数集中处理，当子类和父类对象都被Hook了，且子类调用了super后，就会造成递归。所以如果两个VC存在继承关系且都实现tableViewdeletegate，且在子类调用了super，必定会造成递归。
demo如下：
@interface Parent:NSObject
@property(copy,nonatomic) NSString *name;
-(void) showName;
@end
@implementation Parent
-(void) showName {
    NSLog(@"showName: %@",_name);
}
@end

@interface Child : Parent

@end
@implementation Child

-(void) showName {
    [super showName];
    NSLog(@"this is chiled");
}

@end

-(void) hookTest {
    [GrowingSwizzler growing_swizzleSelector:@selector(showName) onClass:[Parent class] withBlock:^(id name,SEL sel){
        NSLog(@"hooked:%@",name);
    } named:@"showName"];
    
    [GrowingSwizzler growing_swizzleSelector:@selector(showName) onClass:[Child class] withBlock:^(id name,SEL sel){
        NSLog(@"hooked:%@",name);
    } named:@"showName2"];
    
    Parent * parent = [Parent new];
    parent.name = @"father";
    [parent showName];
    
    Child *child = [Child new];
    child.name = @"child";
    [child showName];
}

**Comment by shiflymoon** [comment]
基于三方开源的简单做了一个可以解决递归的解决方案：https://github.com/shiflymoon/SEMethodSwizzier

**Comment by YoloMao** [comment]
相对于对 Cocoa Touch 视图基类的埋点，用常见的 JRSwizzle 来 Hook 用户事件即可；
但 Delegate.class 的埋点有不确定性，在继承链中，当对父类和子类（未重写父类方法）先后 Hook，会触发 2 次 trackEvent，我想这也是采用 GrowingSwizzler 的一个原因；
GrowingSwizzler 正如 @shiflymoon 所说的情况下，会由于 super 的特性发生无限递归，这里基于 RSSwizzle 实现，添加了 mode RSSwizzleModeOnceInTheInheritanceChain，对象继承链中只 Hook 一次同一方法，保证 trackEvent 只执行一次，具体可以看：
[RSSwizzleDemo](https://github.com/YoloMao/RSSwizzleDemo)
[RSSwizzle](https://github.com/rabovik/RSSwizzle/)

RSSwizzle 虽然强大，但也有缺陷，当对父类和子类（重写了父类方法，并调用 super 实现）同时 Hook，会触发 2 次 trackEvent（无法避免），要解决这种问题，用动态子类的方式来 Hook 应该是最佳方案，但动态子类对性能和内存的影响相对于 Runtime Swizzling 较大。

**Comment by YoloMao** [comment]
预计在 SDK 4.x 上修复该场景下的问题，感谢您的意见
